# Generated by Django 5.1.6 on 2026-01-03 10:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0003_alter_apikey_is_active_alter_apikey_name'),
        ('sendFile', '0002_alter_userdetails_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employes.employes'),
        ),
    ]
