# Generated by Django 5.1.6 on 2026-01-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employes', '0002_apikey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
